services:
  cli:
    container_name: php-cli
    image: php:8.2-cli
    entrypoint: bash
    tty: true
    build:
      context: ./.docker/php-cli
      dockerfile: Dockerfile
    pull_policy: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"