services:
  cli:
    container_name: php-cli
    image: php:8.2-cli
    entrypoint: bash
    tty: true
    build:
      context: ./.docker/php-cli
      dockerfile: Dockerfile
    pull_policy: always
    volumes:
      - .:/app

  app:
    container_name: app
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - discount-calculator

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80" # Expose port 80 of the container as port 8080 on localhost
    volumes:
      - ./:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - discount-calculator

networks:
  discount-calculator:
    driver: bridge